targets:

  archer-c7-v5-initramfs:
    resources:
      RawSerialPort:
        port: "/dev/archer-c7-v5"
    drivers:
      ExternalPowerDriver:
        cmd_on: ssh root@uart-relay.testbed.vpn.true.cz power_on 3
        cmd_off: ssh root@uart-relay.testbed.vpn.true.cz power_off 3
      SerialDriver: {}
      ShellDriver:
        console_ready: Please press Enter to activate this console.
        prompt: 'root@[\w()]+:[^ ]+ '
        login_prompt: built-in shell (ash)
        await_login_timeout: 15
        username: kingbanik
      SmallUBootDriver:
        prompt: 'ath> '
        boot_expression: 'Hit any key to stop autoboot'
        init_commands:
          - setenv serverip 192.168.1.2
          - setenv ipaddr 192.168.1.1
          - setenv bootargs debug earlyprintk console=ttyS0,115200
          - ping 192.168.1.2; ping 192.168.1.2; ping 192.168.1.2
          - tftpboot 0x81000000 openwrt-ath79-generic-tplink_archer-c7-v5-initramfs-kernel.bin
      UBootStrategy: {}

  glinet-b1300-initramfs:
    resources:
      RawSerialPort:
        port: "/dev/glinet-b1300"
    drivers:
      ExternalPowerDriver:
        cmd_on: ssh root@uart-relay.testbed.vpn.true.cz power_on 1
        cmd_off: ssh root@uart-relay.testbed.vpn.true.cz power_off 1
      SerialDriver: {}
      ShellDriver:
        console_ready: Please press Enter to activate this console.
        prompt: 'root@[\w()]+:[^ ]+ '
        login_prompt: built-in shell (ash)
        await_login_timeout: 15
        username: kingbanik
      UBootDriver:
        prompt: '\(IPQ40xx\) # '
        password: 'gl'
        password_prompt: 'Hit "gl" key to stop booting'
        init_commands:
          - setenv bootdelay 0
          - setenv serverip 192.168.1.2
          - setenv ipaddr 192.168.1.1
          - setenv tftpimage openwrt-ipq40xx-generic-glinet_gl-b1300-initramfs-fit-uImage.itb
        boot_command_delay: 5
        boot_command: tftpboot 0x83000000 $tftpimage && bootm 0x83000000
      UBootStrategy: {}

  glinet-b1300-nor:
    resources:
      RawSerialPort:
        port: "/dev/glinet-b1300"
    drivers:
      ExternalPowerDriver:
        cmd_on: ssh root@uart-relay.testbed.vpn.true.cz power_on 1
        cmd_off: ssh root@uart-relay.testbed.vpn.true.cz power_off 1
      SerialDriver: {}
      ShellDriver:
        console_ready: Please press Enter to activate this console.
        prompt: 'root@[\w()]+:[^ ]+ '
        login_prompt: built-in shell (ash)
        await_login_timeout: 15
        username: kingbanik
      UBootDriver:
        prompt: '\(IPQ40xx\) # '
        password: 'gl'
        password_prompt: 'Hit "gl" key to stop booting'
        init_commands:
          - setenv bootdelay 0
          - setenv serverip 192.168.1.2
          - setenv ipaddr 192.168.1.1
        boot_command_delay: 5
        boot_timeout: 180
        boot_command: tftpboot 0x84000000 openwrt-ipq40xx-generic-glinet_gl-b1300-squashfs-sysupgrade.bin && sf probe && sf erase 0x180000 0x1e80000 && sf write 0x84000000 0x180000 $filesize && bootipq
      UBootStrategy: {}

  # needs patched u-boot for emmc r/w https://lists.denx.de/pipermail/u-boot/2021-February/441964.html
  turris-omnia-emmc:
    resources:
      RawSerialPort:
        port: "/dev/turris-omnia"
    drivers:
      ExternalPowerDriver:
        cmd_on: ssh root@uart-relay.testbed.vpn.true.cz power_on 0
        cmd_off: ssh root@uart-relay.testbed.vpn.true.cz power_off 0
      SerialDriver:
        txdelay: 0.01
      ShellDriver:
        console_ready: Please press Enter to activate this console.
        prompt: 'root@[\w()]+:[^ ]+ '
        login_prompt: built-in shell (ash)
        await_login_timeout: 15
        username: kingbanik
      UBootDriver:
        prompt: '=> '
        init_commands:
          - setenv bootargs earlyprintk console=ttyS0,115200
          - setenv set_blkcnt 'setexpr blkcnt ${filesize} + 0x1ff && setexpr blkcnt ${blkcnt} / 0x200'
          - dhcp ${kernel_addr_r} openwrt-mvebu-cortexa9-cznic_turris-omnia-sysupgrade.img
        boot_command: run set_blkcnt && mmc dev 0 0 && mmc erase 0 ${blkcnt} && mmc write ${kernel_addr_r} 0 ${blkcnt} && run bootcmd
      UBootStrategy: {}

  turris-omnia-initramfs:
    resources:
      RawSerialPort:
        port: "/dev/turris-omnia"
    drivers:
      ExternalPowerDriver:
        cmd_on: ssh root@uart-relay.testbed.vpn.true.cz power_on 0
        cmd_off: ssh root@uart-relay.testbed.vpn.true.cz power_off 0
      SerialDriver:
        txdelay: 0.01
      ShellDriver:
        console_ready: Please press Enter to activate this console.
        prompt: 'root@[\w()]+:[^ ]+ '
        login_prompt: built-in shell (ash)
        await_login_timeout: 15
        username: kingbanik
      UBootDriver:
        prompt: '=> '
        init_commands:
          - setenv bootargs earlyprintk console=ttyS0,115200
          - dhcp ${kernel_addr_r} openwrt-mvebu-cortexa9-cznic_turris-omnia-initramfs-kernel.bin
        boot_command: bootm ${kernel_addr_r}
      UBootStrategy: {}
