build Docker image testbed:
  stage: docker
  extends: .build Docker image
  variables:
    DOCKER_DOCKERFILE_PATH: .gitlab/docker/testbed

test Docker image testbed:
  stage: docker test
  extends: .docker in docker
  needs: ["build Docker image testbed"]
  script:
    - export IMAGE_NAME="$(echo $CI_JOB_NAME | sed 's/test Docker image \(.*\)/\1/')"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG"
    - >
      docker run --rm "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG" sh -c "
      python3 -c 'import labgrid; import yaml'
      "

deploy Docker image testbed:
  stage: docker deploy
  extends: .deploy Docker image
  needs: ["test Docker image testbed"]
