name: Build Testing Kernel

on:
  pull_request:
    paths:
      - '.github/workflows/kernel*.yml'
      - 'include/kernel-*'
      - 'package/kernel/**'
      - 'target/linux/generic/**'
jobs:
  build_testing_kernel:
    uses: ./.github/workflows/kernel-reusable.yml
    with:
      config_seed: 'CONFIG_ALL_KMODS=y\nCONFIG_TESTING_KERNEL=y\n'
